# Generated by Django 4.2.25 on 2025-11-08 08:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("custom", "Custom"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                (
                    "tracking_type",
                    models.CharField(
                        choices=[
                            ("boolean", "Yes/No (One-time mark)"),
                            ("counter", "Counter (Multiple times)"),
                        ],
                        default="boolean",
                        max_length=20,
                    ),
                ),
                (
                    "target_value",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Target value for counter type habits (e.g., 8 glasses of water)",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#2980B9",
                        help_text="Hex color code for visual representation",
                        max_length=7,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon name or emoji", max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Habit",
                "verbose_name_plural": "Habits",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyReflection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "day_rating",
                    models.PositiveIntegerField(
                        help_text="Rate your day from 1-10",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("terrible", "Terrible"),
                            ("bad", "Bad"),
                            ("okay", "Okay"),
                            ("good", "Good"),
                            ("excellent", "Excellent"),
                            ("peak", "Peak"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "mood_intensity",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Intensity of the mood from 1-10",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional thoughts or reflections"
                    ),
                ),
                (
                    "gratitude",
                    models.TextField(
                        blank=True, help_text="What are you grateful for today?"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_reflections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Reflection",
                "verbose_name_plural": "Daily Reflections",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="HabitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "value",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="1 for boolean habits, actual count for counter habits",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="habit_tracker.habit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Habit Log",
                "verbose_name_plural": "Habit Logs",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["habit", "-date"], name="habit_track_habit_i_203dc5_idx"
                    ),
                    models.Index(fields=["date"], name="habit_track_date_8b12d9_idx"),
                ],
                "unique_together": {("habit", "date")},
            },
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(
                fields=["user", "is_active"], name="habit_track_user_id_541808_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyreflection",
            index=models.Index(
                fields=["user", "-date"], name="habit_track_user_id_d5ff86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyreflection",
            index=models.Index(fields=["date"], name="habit_track_date_da51b0_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="dailyreflection",
            unique_together={("user", "date")},
        ),
    ]
