# Generated by Django 4.2.25 on 2025-11-07 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiaryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diary_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Diary Entry",
                "verbose_name_plural": "Diary Entries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("video", "Video"),
                        ],
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("text_content", models.TextField(blank=True, null=True)),
                (
                    "media_file",
                    models.FileField(
                        blank=True, null=True, upload_to="diary_media/%Y/%m/%d/"
                    ),
                ),
                ("media_url", models.URLField(blank=True, null=True)),
                ("caption", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "diary_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_blocks",
                        to="diary.diaryentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Block",
                "verbose_name_plural": "Content Blocks",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="diaryentry",
            index=models.Index(
                fields=["-created_at"], name="diary_diary_created_030474_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diaryentry",
            index=models.Index(
                fields=["author", "-created_at"], name="diary_diary_author__f5e32a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentblock",
            index=models.Index(
                fields=["diary_entry", "order"], name="diary_conte_diary_e_50b375_idx"
            ),
        ),
    ]
