# Generated by Django 4.2.25 on 2025-11-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentblock",
            name="media_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
