# Generated by Django 4.2.25 on 2026-03-17 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("diary", "0002_alter_contentblock_media_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiaryTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diary_tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Diary Tag",
                "verbose_name_plural": "Diary Tags",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="diaryentry",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="entries", to="diary.diarytag"
            ),
        ),
        migrations.AddIndex(
            model_name="diarytag",
            index=models.Index(
                fields=["author", "name"], name="diary_diary_author__77685d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="diarytag",
            constraint=models.UniqueConstraint(
                fields=("author", "name"), name="unique_diary_tag_per_user"
            ),
        ),
    ]
