# Generated by Django 4.2.25 on 2025-12-02 14:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReflectionQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=500)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("range", "Range (1-10)"),
                            ("choice", "Multiple Choice"),
                            ("text", "Text Response"),
                        ],
                        default="range",
                        max_length=10,
                    ),
                ),
                (
                    "min_value",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "max_value",
                    models.IntegerField(
                        default=10,
                        validators=[django.core.validators.MaxValueValidator(10)],
                    ),
                ),
                (
                    "choices",
                    models.JSONField(
                        blank=True,
                        help_text="List of choices for multiple choice questions",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this question is currently being used",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Category like 'Productivity', 'Wellness', etc.",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Reflection Question",
                "verbose_name_plural": "Reflection Questions",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SelfReflection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional thoughts or notes for the day"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="self_reflections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Self Reflection",
                "verbose_name_plural": "Self Reflections",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ReflectionResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "range_response",
                    models.IntegerField(
                        blank=True,
                        help_text="Response for range-type questions",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "choice_response",
                    models.CharField(
                        blank=True,
                        help_text="Response for multiple choice questions",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "text_response",
                    models.TextField(
                        blank=True,
                        help_text="Response for text-type questions",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "daily_reflection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="self_reflection.selfreflection",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="self_reflection.reflectionquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reflection Response",
                "verbose_name_plural": "Reflection Responses",
            },
        ),
        migrations.AddIndex(
            model_name="reflectionquestion",
            index=models.Index(
                fields=["is_active", "order"], name="self_reflec_is_acti_0aef4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="selfreflection",
            index=models.Index(
                fields=["user", "-date"], name="self_reflec_user_id_22131a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="selfreflection",
            index=models.Index(fields=["-date"], name="self_reflec_date_ad71c0_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="selfreflection",
            unique_together={("user", "date")},
        ),
        migrations.AddIndex(
            model_name="reflectionresponse",
            index=models.Index(
                fields=["daily_reflection", "question"],
                name="self_reflec_daily_r_c726a4_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reflectionresponse",
            unique_together={("daily_reflection", "question")},
        ),
    ]
