# Generated by Django 4.2.25 on 2025-12-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("self_reflection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reflectionquestion",
            name="color_mapping",
            field=models.JSONField(
                blank=True, help_text="Color mapping for options/values", null=True
            ),
        ),
    ]
