# Generated by Django 4.2.25 on 2026-01-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("self_reflection", "0002_reflectionquestion_color_mapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="reflectionresponse",
            name="number_response",
            field=models.FloatField(
                blank=True,
                help_text="Response for number-type questions (integer or decimal)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reflectionquestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("range", "Range (1-10)"),
                    ("choice", "Multiple Choice"),
                    ("text", "Text Response"),
                    ("number", "Number Input"),
                ],
                default="range",
                max_length=10,
            ),
        ),
    ]
