# Generated by Django 4.2.25 on 2026-01-23 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("self_reflection", "0003_reflectionresponse_number_response_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reflectionquestion",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner/creator of this question",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reflection_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
