# Generated by Django 4.2.25 on 2025-10-19 07:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="user",
            name="social_id",
        ),
    ]
